# Generated by Django 3.2.9 on 2022-04-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=20)),
                ('email', models.EmailField(help_text='enter your vaild email', max_length=30)),
                ('password', models.CharField(help_text='enter your strong password', max_length=20)),
            ],
        ),
    ]
